#!/usr/bin/env bash
# Opt into the mold linker for local Linux builds.
#
# Writes .cargo/config.toml, which is GITIGNORED on purpose: jkbase builds this
# repo in a sealed, offline buildpack VM that we cannot install packages into,
# and a committed config demanding mold would fail the deploy at link time with
# no way to fix it from here. So mold stays a per-developer opt-in — run this
# script once per clone.
#
#   ./scripts/setup-mold.sh              enable mold
#   ./scripts/setup-mold.sh --disable    remove the generated config
#
# Only the host x86_64-unknown-linux-gnu target is touched. wasm32 links with
# rust-lld and is deliberately left alone.

set -euo pipefail

repo_root="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
config="$repo_root/.cargo/config.toml"
marker="# generated by scripts/setup-mold.sh"

if [[ "${1:-}" == "--disable" ]]; then
    if [[ -f "$config" ]] && grep -qF "$marker" "$config"; then
        rm "$config"
        rmdir "$repo_root/.cargo" 2>/dev/null || true
        echo "mold disabled: removed $config"
    else
        echo "nothing to do: $config is absent or not ours to remove"
    fi
    exit 0
fi

if [[ "$(uname -s)" != "Linux" ]]; then
    echo "error: this script targets Linux; mold's macOS support is a separate product" >&2
    exit 1
fi

mold_bin="$(command -v mold || true)"
if [[ -z "$mold_bin" ]]; then
    echo "error: mold not found on PATH." >&2
    echo "  Debian/Ubuntu: sudo apt install mold" >&2
    echo "  Fedora:        sudo dnf install mold" >&2
    echo "  Arch:          sudo pacman -S mold" >&2
    exit 1
fi

if ! command -v clang >/dev/null; then
    echo "error: clang not found on PATH; it is used as the linker driver that hands off to mold." >&2
    echo "  Debian/Ubuntu: sudo apt install clang" >&2
    exit 1
fi

# Refuse to clobber a config this script did not write — it may hold unrelated
# settings (a [patch] for local rinch co-dev, registry config, ...).
if [[ -f "$config" ]] && ! grep -qF "$marker" "$config"; then
    echo "error: $config already exists and was not generated by this script." >&2
    echo "Merge these lines into it by hand instead:" >&2
    echo >&2
    echo "  [target.x86_64-unknown-linux-gnu]" >&2
    echo "  linker = \"clang\"" >&2
    echo "  rustflags = [\"-C\", \"link-arg=--ld-path=$mold_bin\"]" >&2
    exit 1
fi

mkdir -p "$repo_root/.cargo"
cat > "$config" <<EOF
$marker — local opt-in, gitignored, safe to delete.
# Re-run ./scripts/setup-mold.sh to regenerate, or --disable to remove.
#
# Host Linux links go through clang -> mold. wasm32 is NOT listed here: it links
# with rust-lld, where mold does not apply.

[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-C", "link-arg=--ld-path=$mold_bin"]
EOF

echo "mold enabled: wrote $config"
echo "  mold:  $mold_bin ($("$mold_bin" --version | head -1))"
echo "  clang: $(command -v clang)"
echo
echo "Verify with:  cargo build -p plotweb-server && readelf -p .comment target/debug/plotweb-server | grep -i mold"
